### ISSUE TITLE
Unable to make the gitlab example work

### ISSUE THREAD

**Issue by svinther** [minikube-ci/examples#1]
I enjoy using minikube a lot, and I use it for CI at github.com with no problems. I really like to be able to do CI stuff on gitlab as well, but so far no luck with that.

At first the minikube binary will not even run in the Alpine container, so I added `libc6-compat`

Then I got:
_X Exiting due to RSRC_INSUFFICIENT_CORES: Requested cpu count 1 is less than the minimum allowed of 2_

Then I changed the minikube start command to
`./minikube start --extra-config=kubeadm.ignore-preflight-errors=NumCPU --force --cpus=1`

And now it seems to hang forever, last trace line:
_! Listening to 0.0.0.0 on external docker host docker. Please be advised_

Here is the full modified .gitlab-ci.yml
```yaml
image: docker:stable
variables:
  KUBECTL: v1.17.0
services:
  - docker:dind
stages:
  - test
test:
  stage: test
  script:
    - apk add -U wget libc6-compat
    - wget -O ./minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    - chmod +x ./minikube
    - wget -O ./kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - ./minikube start --extra-config=kubeadm.ignore-preflight-errors=NumCPU --force --cpus=1
    - ./kubectl get nodes -o wide
    - ./kubectl get pods --all-namespaces -o wide
    - ./kubectl get services --all-namespaces -o wide
```

Any ideas ?

**Comment by osmedd** [comment]
Is there any expectation minikube should work under a docker:latest / docker:dind setup on a private GitLab instance? Looking at the minikube logging it seems like the k8s container starts up almost completely, it emits some message about a graphical user interface and that is where it hangs.

I guess I am curious whether anyone can confirm it should work or whether I am wasting my time trying.

Thanks.

**Comment by pazepaze** [comment]
There is an alpine package in the edge/testing repository and I actually made minikube start doing something like:

```yaml
  image: docker:28
  # ... e.g. set DOCKER_* vars
  services:
    - docker:28-dind
  script:
      apk add --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing minikube
```

But I wasn't sure how stable a setup like this would be.

Ultimately I just used a ubuntu or debian based image and installed docker and minikube. That seemed like the better approach. So something like this:

```yaml
variables:
  KUBECTL: v1.32.3
  DOCKER_CE_CLI: 28.0.4-1~ubuntu.24.04~noble

stages:
  - test
test:
  image: ubuntu:24.04
  services:
    - docker:28-dind
  stage: test
  script:
    # install Docker
    - apt-get update -qq
    - apt-get install -qq --yes --no-install-recommends ca-certificates curl
    - curl -sSLo ./docker-ce-cli.deb https://download.docker.com/linux/ubuntu/dists/noble/pool/stable/amd64/docker-ce-cli_${DOCKER_CE_CLI}_amd64.deb
    - apt-get install -qq --yes --no-install-recommends ./docker-ce-cli.deb
    # test Docker
    # note: set DOCKER_* vars depending on runner configuration, see https://docs.gitlab.com/ci/docker/using_docker_build/#use-docker-in-docker
    - echo DOCKER_HOST=$DOCKER_HOST
    - echo DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY
    - echo DOCKER_CERT_PATH=$DOCKER_CERT_PATH
    - echo DOCKER_TLS_CERTDIR=$DOCKER_TLS_CERTDIR
    - docker info
    # install Minikube
    - curl -sSLo ./minikube https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
    - install minikube /usr/local/bin/minikube
    # install kubectl
    - curl -sSLo ./kubectl https://dl.k8s.io/release/$KUBECTL/bin/linux/amd64/kubectl
    - install kubectl /usr/local/bin/kubectl
    # start minikube, could also use --wait=all
    - minikube start --force
    # test minikube
    - kubectl get nodes -o wide
    - kubectl get pods --all-namespaces -o wide
    - kubectl get services --all-namespaces -o wide
    - minikube delete --all
```
